### ISSUE TITLE
bggcli fails with new BoardGameGeek game page interface

### ISSUE THREAD

**Issue by commadelimited** [syllant/bggcli#3]
The bggcli export tool works flawlessly.

The bggcli import tool works fails when attempting to access elements on the new board game page interface. I'm including a stack trace here:

```
[bggcli] Importing games for '<account_name>' account...
[bggcli] Authenticating... [done]
[bggcli] Importing 108 games...
[bggcli] [1/108] Custom Heroes... [bggcli] ERROR: Unexpected error while controlling the UI!
Either the web pages have changed and bggcli must be updated, or the site is down for maintenance.
Cause: Message: Unable to locate element: (//a[contains(@onclick, 'CE_ModuleAddItem')])[last()]

Traceback (most recent call last):
  File "/Users/andymatthews/.virtualenvs/bgg/lib/python2.7/site-packages/bggcli/util/csvreader.py", line 60, in iterate
    callback(row)
  File "/Users/andymatthews/.virtualenvs/bgg/lib/python2.7/site-packages/bggcli/commands/collection_import.py", line 50, in <lambda>
    csv_reader.iterate(lambda row: game_page.update(row))
  File "/Users/andymatthews/.virtualenvs/bgg/lib/python2.7/site-packages/bggcli/ui/gamepage.py", line 102, in update
    "(//a[contains(@onclick, 'CE_ModuleAddItem')])[last()]").click()
  File "/Users/andymatthews/.virtualenvs/bgg/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 365, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/andymatthews/.virtualenvs/bgg/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 843, in find_element
    'value': value})['value']
  File "/Users/andymatthews/.virtualenvs/bgg/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/andymatthews/.virtualenvs/bgg/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
```

For reference here's the BGG page for the game being added (Custom Heroes):
https://boardgamegeek.com/boardgame/223049/custom-heroes

**Comment by HiGregSmith** [comment]
My fork works with the current version of boardgamegeek.com

https://github.com/HiGregSmith/bggcli
